version: '1.0'

services:
  dragndrop:
    image: dragndrop
    build: .
    environment:
      NODE_ENV: production
    ports:
<<<<<<< HEAD
      - 80:5000
=======
      - 80:5000
>>>>>>> d21ac5eca924a38d2b5e7b62eb54e692180bbeb5
